services:
  bring-api:
    build:
      context: .
    container_name: bring_api
    ports:
      - "9000:8000"
    environment:
      - BRING_EMAIL=${BRING_EMAIL}
      - BRING_PASSWORD=${BRING_PASSWORD}
    restart: unless-stopped
    networks:
      docker:
        ipv4_address: ${IPV4_ADDRESS}

networks:
  docker:
    external: true